name: Update README with Traffic Info

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Get Traffic Data
        id: traffic
        run: |
          echo "Fetching traffic data..."
          response=$(curl -H "Accept: application/vnd.github.v3+json" \
                       -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                       https://api.github.com/repos/${{ github.repository }}/traffic/views)
          echo "Raw Response: $response"  # Print the raw response for debugging
          views=$(echo $response | jq '.count')
          uniques=$(echo $response | jq '.uniques')
          echo "Parsed Views: $views"
          echo "Parsed Uniques: $uniques"
          echo "::set-output name=views::$views"
          echo "::set-output name=unique::$uniques"

      - name: Update README
        run: |
          VIEWS=${{ steps.traffic.outputs.views }}
          UNIQUES=${{ steps.traffic.outputs.unique }}
          DATE=$(date '+%Y-%m-%d')
          echo "Updating README.md..."
          # Remove old Traffic Info section
          sed -i '/## Traffic Info/,/^$/d' README.md
          # Insert new Traffic Info section at the top
          echo -e "## Traffic Info\nLast updated: $DATE\n\n* Total Views: $VIEWS\n* Unique Visitors: $UNIQUES\n\n$(cat README.md)" > README.md

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "Update README with traffic info"
          git push origin main
