name: Update README with Traffic Info

# Define when the workflow should be triggered
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:  # Runs on every push to the repository
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write  # Grants write permission to contents

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main  # Ensure the main branch is checked out

      - name: Get Traffic Data
        id: traffic
        run: |
          echo "Fetching traffic data..."
          response=$(curl -H "Accept: application/vnd.github.v3+json" \
                       -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                       https://api.github.com/repos/${{ github.repository }}/traffic/views)
          echo "Response: $response"  # Print the raw response for debugging
          views=$(echo $response | jq '.count')
          uniques=$(echo $response | jq '.uniques')
          echo "Views: $views"
          echo "Uniques: $uniques"
          echo "::set-output name=views::$views"
          echo "::set-output name=unique::$uniques"

      - name: Update README
        run: |
          VIEWS=${{ steps.traffic.outputs.views }}
          UNIQUES=${{ steps.traffic.outputs.unique }}
          DATE=$(date '+%Y-%m-%d')
          echo "Updating README.md..."
          # Insert or update the traffic section at the top of the README
          awk -v views="$VIEWS" -v uniques="$UNIQUES" -v date="$DATE" '
            BEGIN { print "## Traffic Info\nLast updated: " date "\n\n* Total Views: " views "\n* Unique Visitors: " uniques "\n" }
            NR>1 { print }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "Update README with traffic info"
          git push origin HEAD:main
