name: Update README with Traffic Info

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main  # Checkout the main branch initially

      - name: Create or Checkout main2 Branch
        run: |
          git fetch origin main2 || echo "Branch main2 does not exist. Creating it."
          git checkout main2 || git checkout -b main2
          git push origin main2

      - name: Get Traffic Data
        id: traffic
        run: |
          echo "Fetching traffic data..."
          response=$(curl -H "Accept: application/vnd.github.v3+json" \
                       -H "Authorization: token ${{ secrets.FINE_GRAINED_TOKEN }}" \
                       https://api.github.com/repos/${{ github.repository }}/traffic/views)
          echo "Raw Response: $response"  # Print the raw response for debugging
          views=$(echo $response | jq '.count')
          uniques=$(echo $response | jq '.uniques')
          echo "Parsed Views: $views"
          echo "Parsed Uniques: $uniques"
          echo "::set-output name=views::$views"
          echo "::set-output name=unique::$uniques"

      - name: Update README
        run: |
          VIEWS=${{ steps.traffic.outputs.views }}
          UNIQUES=${{ steps.traffic.outputs.unique }}
          DATE=$(date '+%Y-%m-%d')
          echo "Updating README.md..."
          # Create the new Traffic Info section
          new_traffic_info=$(echo -e "## Traffic Info\nLast updated: $DATE\n\n* Total Views: $VIEWS\n* Unique Visitors: $UNIQUES\n\n")
          # Remove old Traffic Info section and insert the new one at the top
          awk -v new_info="$new_traffic_info" '
            BEGIN { print new_info }
            $0 !~ /^## Traffic Info$/ && $0 !~ /^Last updated:/ && $0 !~ /^\* Total Views:/ && $0 !~ /^\* Unique Visitors:/ { print }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and Push Changes
        env:
          FINE_GRAINED_TOKEN: ${{ secrets.FINE_GRAINED_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.FINE_GRAINED_TOKEN }}@github.com/${{ github.repository }}.git
          git pull origin main2 --rebase  # Pull latest changes from remote before pushing
          git add README.md
          git commit -m "Update README with traffic info"
          git push origin main2
