name: Update README with Traffic Info

# Define when the workflow should be triggered
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:  # Runs on every push to the repository
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Traffic Data
        id: traffic
        run: |
          echo "Fetching traffic data..."
          response=$(curl -H "Accept: application/vnd.github.v3+json" \
                       -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                       https://api.github.com/repos/${{ github.repository }}/traffic/views)
          echo "::set-output name=views::$(echo $response | jq '.count')"
          echo "::set-output name=unique::$(echo $response | jq '.uniques')"

      - name: Update README
        run: |
          VIEWS=${{ steps.traffic.outputs.views }}
          UNIQUES=${{ steps.traffic.outputs.unique }}
          DATE=$(date '+%Y-%m-%d')
          echo "Updating README.md..."
          sed -i '/## Traffic Info/,$ d' README.md
          echo "## Traffic Info\n" >> README.md
          echo "Last updated: $DATE\n" >> README.md
          echo "* Total Views: $VIEWS\n" >> README.md
          echo "* Unique Visitors: $UNIQUES\n" >> README.md

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "Update README with traffic info"
          git push origin HEAD:main
